language: node_js
node_js:
- "stable"
services:
  - postgresql
before_script:
  - psql -c 'create database db_events_test;' -U postgres
  - npm run seed
cache:
  directories:
    - "node_modules"
env:
 global:
   - export NODE_ENV=test
install:
  - npm install
script:
  - npm test
after_success: npm run coveralls
